### PR TITLE
removed initial list

### PR DESCRIPTION
**Pull request by xingmeizhi**
implement #30 #42

### CODE REVIEW

**Comment by msereeyothin** [comment]
nice
do you want to make this better by updating how 'loading' looks. Maybe add like a spinning wheel in the center or something

**Comment by xingmeizhi** [comment]
Xnip2024-04-10_18-57-26
Implemented using this package: https://www.npmjs.com/package/react-spinners

**Comment by msereeyothin** [comment]
everything looks good, can you just add some vertical padding so it isn't so close to the search bar and also make it slightly smaller. Im planning to overhaul the color and theme later so u can just leave it.

**Comment by xingmeizhi** [comment]
make sure to run npm install lodash

**Comment by msereeyothin** [comment]
nice work

**Pull request merged**
